version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ledotta
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: ledotta
volumes:
  db_data: {}