version: "3.9"
    
services:
  db:
    hostname: "ledotta_db"
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql:rw
      - ./db_data.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    restart: always
    ports:
      - "3311:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ledotta
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3311
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: ledotta
volumes:
  db_data: {}